name: screen_tester
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tmcmaster/screen_tester/blob/main/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  #pixel_perfect: ^1.1.0
  device_preview: ^0.7.3
  flutter_riverpod:
  sprintf:
  theme_builder:
    path: ../theme_builder
#    git:
#      url: https://github.com/tmcmaster/theme_builder.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  lint:
  test:

  flutter_workbench:
    path: ../flutter_workbench
#    git:
#      url: https://github.com/tmcmaster/flutter_workbench.git