name: screen_tester
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tmcmaster/screen_tester/blob/main/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  pixel_perfect: ^1.1.0
  device_preview: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  lint:
  test:
  flutter_workbench:
    path: ../flutter_workbench
  widget_tester:
    path: ../widget_tester
  theme_builder:
    path: ../theme_builder